tasks:
  - name: hackingtool
    command: |
      chmod -R 755 hackingtool  
      sudo pip3 install -r requirement.txt
      echo "1" | sudo bash install.sh
      echo "2" | sudo hackingtool

## Ports to expose on workspace startup
#ports:
#  - port: 8080
#    onOpen: open-preview
#    name: ttyd
